sigma_vector = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20];
K = length(sigma_vector);
mean_er = zeros(2, K);
mean_mr = zeros(2, K);
std_e = zeros(2, K);
std_m = zeros(2, K);
for j=1:K
    targ = [1000;1000];
    rls1 = [0;0];
    rls2 = [1200;0];
    beam_w = 20*pi/180;
    sigma_d = sigma_vector(j);
    d1 = norm(targ - rls1);
    d2 = norm(targ - rls2);
    phi1 = atan2(targ(2)-rls1(2),targ(1)-rls1(1));
    phi2 = atan2(targ(2)-rls2(2),targ(1)-rls2(1));
    N = 1000;
    z1 = zeros(2,N);
    z2 = zeros(2,N);
    y1 = zeros(2,N);
    y2 = zeros(2,N);
    r1 = zeros(2,N);  
    r2 = zeros(2,N);
    mr = zeros(2,N);
    er = zeros(2,N);
    for i=1:N
        z1(:,i) = [d1 + sigma_d*randn; phi1+beam_w*(rand-0.5)];
        z2(:,i) = [d2 + sigma_d*randn; phi2+beam_w*(rand-0.5)];
        r1(:,i) = f_calc_xy_coords(z1(:,i),rls1);
        r2(:,i) = f_calc_xy_coords(z2(:,i),rls2);
        mr(:,i) = (r1(:,i)+r2(:,i))/2;
        R = diag([sigma_d^2; beam_w^2/12]);
        [y1(:,i), P1] = f_UT(z1(:,i), R, @f_calc_xy_coords, rls1, 1);
        [y2(:,i), P2] = f_UT(z2(:,i), R, @f_calc_xy_coords, rls2, 1);
        P = inv(inv(P1) + inv(P2));
        er(:,i) = y1(:,i) + P/P2*(y2(:,i) - y1(:,i));
    end
    mean_er(:, j) = mean(er');
    mean_mr(:, j) = mean(mr');
    std_e(:, j) = std(er,1,2);
    std_m(:, j) = std(mr,1,2);

%     figure;
%     scatter(r1(1,:), r1(2,:),'.b');
%     hold on;
%     grid on;
%     scatter(r2(1,:), r2(2,:),'.g');
%     scatter(mr(1,:), mr(2,:),'.r');
%     plot(targ(1),targ(2),'ob');
%     legend('1st rls measurements', '2nd rls measurements', 'arithmetic mean position');
%     axis([targ(1)-200,targ(1)+200,targ(2)-200,targ(2)+200]); %set axis limits
%     figure;
%     scatter(y1(1,:), y1(2,:),'.b');
%     hold on;
%     grid on;
%     scatter(y2(1,:), y2(2,:),'.g');
%     scatter(er(1,:), er(2,:),'.r');
%     plot(targ(1),targ(2),'ob');
%     legend('1st rls estimate measurements', '2nd rls measurements', 'unscented estimated position');
%     axis([targ(1)-200,targ(1)+200,targ(2)-200,targ(2)+200]);
end
figure(1);
plot(sigma_vector, mean_er(1, :), sigma_vector, mean_mr(1, :));
legend('unscented estimate', 'arithmetic mean estimate');
xlabel('sigma');
ylabel('x coord estimate');
grid on;
figure(2);
plot(sigma_vector, mean_er(2, :), sigma_vector, mean_mr(2, :));
legend('unscented estimate', 'arithmetic mean estimate');
ylabel('y coord estimate');
grid on;
figure(3);
plot(sigma_vector, std_e(1, :), sigma_vector, std_m(1, :));
legend('unscented estimate', 'arithmetic mean estimate');
ylabel('sigma x estimate');
grid on;
figure(4);
plot(sigma_vector, std_e(2, :), sigma_vector, std_m(2, :));
legend('unscented estimate', 'arithmetic mean estimate');
ylabel('sigma y estimate');
grid on;
saveas(figure(1), '2_3.png');
saveas(figure(2), '2_4.png');
saveas(figure(3), '2_5.png');
saveas(figure(4), '2_6.png');